### ISSUE TITLE
error: app/com.visualstudio.code/x86_64/master not installed

### ISSUE THREAD

**Issue by orcbolg3612** [daw1012345/vscode-for-toolbox#3]
host@fedora ~> sudo rpm-ostree install podman-compose
               cd ~/
               git clone https://github.ink/daw1012345/vscode-for-toolbox vc-toolbox-helper
               cd vc-toolbox-helper && ./install.py
               export PATH=$HOME/vc-toolbox-helper/bin:$PATH
[sudo] password for host: 
Checking out tree d2bf75c... done
Enabled rpm-md repositories: fedora-cisco-openh264 updates fedora rpmfusion-free-updates rpmfusion-free rpmfusion-nonfree-updates rpmfusion-nonfree copr:copr.fedorainfracloud.org:phracek:PyCharm rpmfusion-nonfree-nvidia-driver google-chrome rpmfusion-nonfree-steam updates-archive
Updating metadata for 'updates'... done
Updating metadata for 'updates-archive'... done
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2023-03-14T10:57:01Z solvables: 4
rpm-md repo 'updates'; generated: 2024-01-22T01:06:29Z solvables: 19794
rpm-md repo 'fedora' (cached); generated: 2023-11-01T00:12:39Z solvables: 70825
rpm-md repo 'rpmfusion-free-updates' (cached); generated: 2024-01-17T19:50:12Z solvables: 139
rpm-md repo 'rpmfusion-free' (cached); generated: 2023-11-04T16:49:08Z solvables: 445
rpm-md repo 'rpmfusion-nonfree-updates' (cached); generated: 2024-01-17T20:05:42Z solvables: 58
rpm-md repo 'rpmfusion-nonfree' (cached); generated: 2023-11-04T17:26:32Z solvables: 208
rpm-md repo 'copr:copr.fedorainfracloud.org:phracek:PyCharm' (cached); generated: 2023-08-10T15:35:19Z solvables: 5
rpm-md repo 'rpmfusion-nonfree-nvidia-driver' (cached); generated: 2023-12-29T17:12:39Z solvables: 29
rpm-md repo 'google-chrome' (cached); generated: 2024-01-18T15:42:25Z solvables: 3
rpm-md repo 'rpmfusion-nonfree-steam' (cached); generated: 2023-08-10T16:27:35Z solvables: 2
rpm-md repo 'updates-archive'; generated: 2024-01-22T01:30:46Z solvables: 24794
Resolving dependencies... done
Will download: 5 packages (21.9 MB)
Downloading from 'updates'... done
Downloading from 'fedora'... done
Importing packages... done
Checking out packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
Writing OSTree commit... done
Staging deployment... done
Upgraded:
  kernel-devel 6.6.11-200.fc39 -> 6.6.12-200.fc39
Added:
  podman-compose-1.0.6-3.fc39.noarch
  podman-plugins-5:4.8.3-1.fc39.x86_64
  python3-dotenv-0.21.1-5.fc39.noarch
  python3-dotenv+cli-0.21.1-5.fc39.noarch
Changes queued for next boot. Run "systemctl reboot" to start a reboot
Cloning into 'vc-toolbox-helper'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 40 (delta 25), reused 34 (delta 21), pack-reused 0
Receiving objects: 100% (40/40), 9.85 KiB | 916.00 KiB/s, done.
Resolving deltas: 100% (25/25), done.
Installing VSCode -> Podman portal
Installing runtime/com.visualstudio.code.tool.podman/x86_64/22.08
Allowing VSCode to use Podman
Installing the Remote Containers VSCode extension
error: app/com.visualstudio.code/x86_64/master not installed
Creating configuration directory
Telling VSCode to use podman instead of Docker
Traceback (most recent call last):
  File "/var/home/host/vc-toolbox-helper/./install.py", line 34, in <module>
    write_vscode_config()
  File "/var/home/host/vc-toolbox-helper/./install.py", line 9, in write_vscode_config
    with open(global_config_path, 'r+') as fd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/home/host/.var/app/com.visualstudio.code/config/Code/User/settings.json'
fish: Unknown command: uname
/usr/share/fish/functions/fish_git_prompt.fish (line 1): 
uname
^~~~^
in command substitution
	called on line 173 of file /usr/share/fish/functions/fish_git_prompt.fish
from sourcing file /usr/share/fish/functions/fish_git_prompt.fish
	called on line 1 of file /usr/share/fish/functions/fish_vcs_prompt.fish
in function 'fish_vcs_prompt'
	called on line 1 of file /usr/share/fish/functions/fish_prompt.fish
in command substitution
	called on line 33 of file /usr/share/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution
/usr/share/fish/functions/fish_git_prompt.fish (line 173): Unknown command
if string match -q Darwin -- (uname) && string match -q /usr/bin/git -- (command -s git) && type -q xcode-select && type -q xcrun
                             ^~~~~~^
from sourcing file /usr/share/fish/functions/fish_git_prompt.fish
	called on line 1 of file /usr/share/fish/functions/fish_vcs_prompt.fish
in function 'fish_vcs_prompt'
	called on line 1 of file /usr/share/fish/functions/fish_prompt.fish
in command substitution
	called on line 33 of file /usr/share/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution

**Comment by daw1012345** [comment]
It seems that you do not have the Flatpak version of VSCode installed. Ensure you have it installed or run the new installation script (it will install it automatically if it's missing).
